import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/ThemeProvider";
import { cn } from "~/lib/utils";
import Navbar from "./_components/Navbar";

import "react-loading-skeleton/dist/skeleton.css";
import "simplebar-react/dist/simplebar.min.css";

import { Toaster } from "~/components/ui/toaster";

export const metadata: Metadata = {
  title: "AI-SaaS",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sans antialiased grainy", geist.className)}>
        <TRPCReactProvider>
          <Toaster />
          <Navbar />
          {children}
          </TRPCReactProvider>
      </body>
    </html>
  );
}
